// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTodoSection: typeof import('./src/components/layout/AddTodoSection/AddTodoSection.vue')['default']
    Dialog: typeof import('./src/components/commons/Dialog/Dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    Input: typeof import('./src/components/commons/Input/Input.vue')['default']
    TodoItem: typeof import('./src/components/layout/TodoListSection/components/TodoItem/TodoItem.vue')['default']
    TodoListSection: typeof import('./src/components/layout/TodoListSection/TodoListSection.vue')['default']
  }
}

export { }
